"""Add current_stage to runs table

Revision ID: 84c3bf335c1d
Revises: b2c4e7f83a1d
Create Date: 2026-02-26 11:50:36.180410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c3bf335c1d'
down_revision: Union[str, Sequence[str], None] = 'b2c4e7f83a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('current_stage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'current_stage')
    # ### end Alembic commands ###
