"""initial schema

Revision ID: 9fde9c88194a
Revises: 
Create Date: 2026-02-25 17:16:04.787240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fde9c88194a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('platform_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('social_urls', sa.JSON(), nullable=True),
    sa.Column('hubspot_contact_id', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_id', name='uq_lead_platform_id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('bdr_assignment', sa.Text(), nullable=True),
    sa.Column('profiles_found', sa.Integer(), nullable=True),
    sa.Column('profiles_pre_screened', sa.Integer(), nullable=True),
    sa.Column('profiles_enriched', sa.Integer(), nullable=True),
    sa.Column('profiles_scored', sa.Integer(), nullable=True),
    sa.Column('contacts_synced', sa.Integer(), nullable=True),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=True),
    sa.Column('tier_distribution', sa.JSON(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('stage_reached', sa.Text(), nullable=True),
    sa.Column('prescreen_result', sa.Text(), nullable=True),
    sa.Column('prescreen_reason', sa.Text(), nullable=True),
    sa.Column('analysis_evidence', sa.JSON(), nullable=True),
    sa.Column('lead_score', sa.Float(), nullable=True),
    sa.Column('manual_score', sa.Float(), nullable=True),
    sa.Column('section_scores', sa.JSON(), nullable=True),
    sa.Column('priority_tier', sa.Text(), nullable=True),
    sa.Column('score_reasoning', sa.Text(), nullable=True),
    sa.Column('synced_to_crm', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_runs')
    op.drop_table('runs')
    op.drop_table('leads')
    # ### end Alembic commands ###
